name: Lung Cancer Prediction

on:
    push:
        branches: [main]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Code checkout to machine
              uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12"
            - name: Install dependency
              run: pip install -r requirements.txt
            - name: Run model building pipeline
              run: python scripts/run_pipeline.py --input data/lung_cancer_dataset.csv --target lung_cancer

            


